# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3ddb20567a12559d7e916df7d4602cceded50173b9d9f24e54f13b16629d519da822845f7d5e039bfddd180a7bb169b649cbca2d3ca07fc25cccdbfaac8b3d43

test:
  secret_key_base: 13fb90044637c742511a7ba06d0df1b8189cda7dfe46a5fed031cb89d55a366469df26ac14a7c81685fb4afa4d2dc74e3674147c2ce00dd041d47be38436f837

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
